"""Pydantic schemas package."""

from backend.schemas.ai_settings import (
    AISetting,
    AISettingHealth,
    AISettingTokenClearResponse,
    AISettingTokenUpdate,
    AISettingUpdate,
    OperationFamily,
)
from backend.schemas.company import Company, CompanyBase, CompanyCreate
from backend.schemas.desirability import (
    DesirabilityFactor,
    DesirabilityFactorBase,
    DesirabilityFactorCreate,
    DesirabilityFactorReorderRequest,
    DesirabilityFactorScore,
    DesirabilityFactorUpdate,
    DesirabilityScore,
)
from backend.schemas.job import (
    ApplicationArtifactType,
    ApplicationMaterial,
    ApplicationMaterialQARequest,
    FitAnalysis,
    FitRecommendation,
    JobDetail,
    JobListItem,
    JobScrapeRequest,
    JobScrapeResponse,
    RequirementLevel,
    RoleStatus,
    RoleStatusChange,
    SalaryInfo,
)
from backend.schemas.skill import Skill, SkillBase, SkillCategory, SkillCreate

__all__ = [
    "Company",
    "CompanyBase",
    "CompanyCreate",
    "AISetting",
    "AISettingHealth",
    "AISettingTokenClearResponse",
    "AISettingTokenUpdate",
    "AISettingUpdate",
    "OperationFamily",
    "DesirabilityFactor",
    "DesirabilityFactorBase",
    "DesirabilityFactorCreate",
    "DesirabilityFactorReorderRequest",
    "DesirabilityFactorScore",
    "DesirabilityFactorUpdate",
    "DesirabilityScore",
    "ApplicationArtifactType",
    "ApplicationMaterial",
    "ApplicationMaterialQARequest",
    "FitAnalysis",
    "FitRecommendation",
    "JobDetail",
    "JobListItem",
    "JobScrapeRequest",
    "JobScrapeResponse",
    "RequirementLevel",
    "RoleStatusChange",
    "RoleStatus",
    "SalaryInfo",
    "Skill",
    "SkillBase",
    "SkillCategory",
    "SkillCreate",
]
